DROP DATABASE IF EXISTS employee_DB;

CREATE DATABASE employee_DB;

USE employee_DB;

CREATE TABLE department (
id INTEGER(11) UNSIGNED AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NULL,
PRIMARY KEY(id)
);

CREATE TABLE role (
id INTEGER(11) UNSIGNED AUTO_INCREMENT NOT NULL,
title VARCHAR(30) UNIQUE NOT NULL,
salary DECIMAL  UNSIGNED NOT NULL,
department_id INTEGER(11) UNSIGNED NOT NULL,
CONSTRAINT fk_dept FOREIGN KEY(department_id) REFERENCES department(id) ON DELETE CASCADE,
PRIMARY KEY(id)
);


CREATE TABLE employee(
id INTEGER(11) UNSIGNED AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER UNSIGNED NOT NULL,
CONSTRAINT fk_role FOREIGN KEY(role_id) REFERENCES role(id) ON DELETE CASCADE,
manager_id INTEGER(11) UNSIGNED, 
PRIMARY KEY(id)
);


